# Generated by Django 5.2.1 on 2025-05-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_provider_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.serviceprovider'),
        ),
    ]
