# Generated by Django 5.2.1 on 2025-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_is_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='brief_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
