# Generated by Django 5.2.1 on 2025-05-08 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_serviceprovider_brief_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_service_provider',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='service_provider_details',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='providers', to='core.service'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='societies',
            field=models.ManyToManyField(blank=True, related_name='service_providers', to='core.society'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
