# Generated by Django 5.2.1 on 2025-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_society_options_society_voting_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='society',
        ),
        migrations.AddField(
            model_name='profile',
            name='societies',
            field=models.ManyToManyField(blank=True, related_name='residents', to='core.society'),
        ),
    ]
