# Generated by Django 5.2.1 on 2025-05-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_profile_society_profile_societies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={},
        ),
        migrations.RemoveField(
            model_name='otp',
            name='expiry_time',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='societies',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='brief_note',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='license_no',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='societies',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='society',
            name='voting_required',
        ),
        migrations.RemoveField(
            model_name='votingrequest',
            name='request_details',
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='residents',
            field=models.ManyToManyField(related_name='societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='society',
            name='service_providers',
            field=models.ManyToManyField(related_name='societies', to='core.serviceprovider'),
        ),
        migrations.AddField(
            model_name='votingrequest',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_voting_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(related_name='service_providers', to='core.service'),
        ),
        migrations.AlterField(
            model_name='society',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='request_type',
            field=models.CharField(choices=[('resident_join', 'Resident Join Request'), ('provider_list', 'Service Provider Listing Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='resident_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting_requests_as_resident', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting_requests_as_provider', to='core.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
