# Generated by Django 5.2.1 on 2025-05-17 16:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_society_options_remove_otp_expiry_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 57, 2, 525137, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_secret',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default='password_reset', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.society'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='brief_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 17, 16, 57, 45, 776427, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='society',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='providers_by_society', to='core.society'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 16, 58, 32, 792787, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='request_type',
            field=models.CharField(choices=[('resident_join', 'Resident Join Request'), ('provider_list', 'Service Provider Listing Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='resident_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='service_provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_request', to='core.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
