# Generated by Django 5.2.1 on 2025-05-18 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_profile_society_profile_societies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='service_providers', to='core.service'),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_voting_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='request_type',
            field=models.CharField(choices=[('resident_join', 'Resident Join'), ('provider_list', 'Service Provider Listing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='resident_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_voting_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_voting_requests', to='core.serviceprovider'),
        ),
    ]
