# Generated by Django 5.2.1 on 2025-05-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_otp_purpose_alter_otp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society_service_providers', to='core.society'),
        ),
    ]
