# Generated by Django 5.2.1 on 2025-05-18 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_serviceprovider_society'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name_plural': 'Societies'},
        ),
        migrations.AlterModelOptions(
            name='votingrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='society',
        ),
        migrations.RemoveField(
            model_name='society',
            name='service_providers',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='societies',
            field=models.ManyToManyField(blank=True, related_name='service_providers', to='core.society'),
        ),
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='initiated_by',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_voting_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='resident_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votingrequest',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_requests', to='core.serviceprovider'),
        ),
    ]
